language: node_js

node_js:
  - '8.9'

sudo: false

os: 
  - linux

dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless

before_script:
  - "npm install"

script: "npm test"

